export { consolePlugin } from "./builtins/console.ts"
export { searchPlugin } from "./builtins/search.ts"
export { Config, ConfigLoadError, ConfigSchema, defineConfig } from "./lib/config.ts"
export { paths } from "./lib/paths.ts"
export type { Hooks, Plugin, RequiredPlugin, RunInput, RunOutput } from "./lib/types.ts"
export { ExecutionError, HookError, Runner } from "./lib/runner.ts"
